### ISSUE TITLE
ReceiverStart java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by ruixiong-kong** [ZhongFuCheng3y/austin#12]
Caused by: java.lang.IndexOutOfBoundsException: Index: 33, Size: 33
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at com.java3y.austin.handler.receiver.kafka.ReceiverStart.lambda$groupIdEnhancer$0(ReceiverStart.java:77)
	at org.springframework.kafka.annotation.KafkaListenerAnnotationBeanPostProcessor.lambda$buildEnhancer$1(KafkaListenerAnnotationBeanPostProcessor.java:321)
	at org.springframework.kafka.annotation.KafkaListenerAnnotationBeanPostProcessor.enhance(KafkaListenerAnnotationBeanPostProcessor.java:418)
	at org.springframework.kafka.annotation.KafkaListenerAnnotationBeanPostProcessor.findListenerAnnotations(KafkaListenerAnnotationBeanPostProcessor.java:400)
	at org.springframework.kafka.annotation.KafkaListenerAnnotationBeanPostProcessor.lambda$postProcessAfterInitialization$2(KafkaListenerAnnotationBeanPostProcessor.java:343)
	at org.springframework.core.MethodIntrospector.lambda$selectMethods$0(MethodIntrospector.java:74)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:364)
	at org.springframework.core.MethodIntrospector.selectMethods(MethodIntrospector.java:72)
	at org.springframework.kafka.annotation.KafkaListenerAnnotationBeanPostProcessor.postProcessAfterInitialization(KafkaListenerAnnotationBeanPostProcessor.java:341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:455)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1808)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	... 23 common frames omitted

**Comment by ruixiong-kong** [comment]
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/31500350/182824793-637d16a6-9f88-40c3-bd3c-3a5664537043.png">

**Comment by ZhongFuCheng3y** [comment]
已Fix，来源于Nacos的初始化操作，可见Gitee issue：https://gitee.com/zhongfucheng/austin/pulls/27
