### ISSUE TITLE
send email error

### ISSUE THREAD

**Issue by wangenji2015** [ZhongFuCheng3y/austin#52]
2023-08-10 09:35:11.376 [dynamic-tp2] ERROR c.java3y.austin.handler.handler.impl.EmailHandler - EmailHandler#handler fail!cn.hutool.extra.mail.MailException: MessagingException: Exception reading response
	at cn.hutool.extra.mail.Mail.send(Mail.java:393)
	at cn.hutool.extra.mail.MailUtil.send(MailUtil.java:416)
	at cn.hutool.extra.mail.MailUtil.send(MailUtil.java:194)
	at cn.hutool.extra.mail.MailUtil.send(MailUtil.java:176)
	at com.java3y.austin.handler.handler.impl.EmailHandler.handler(EmailHandler.java:61)
	at com.java3y.austin.handler.handler.BaseHandler.doHandler(BaseHandler.java:61)
	at com.java3y.austin.handler.pending.Task.run(Task.java:66)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: javax.mail.MessagingException: Exception reading response;
  nested exception is:
	javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:1462)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1260)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:370)
	at javax.mail.Service.connect(Service.java:297)
	at javax.mail.Service.connect(Service.java:156)
	at javax.mail.Service.connect(Service.java:105)
	at javax.mail.Transport.send0(Transport.java:168)
	at javax.mail.Transport.send(Transport.java:98)
	at cn.hutool.extra.mail.Mail.doSend(Mail.java:407)
	at cn.hutool.extra.mail.Mail.send(Mail.java:385)
	... 9 more
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:370)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:313)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:652)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:471)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:367)
	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:376)
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:479)
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:457)
	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:200)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:155)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1320)
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1233)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:417)
	at sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:837)
	at sun.security.ssl.SSLSocketImpl.access$200(SSLSocketImpl.java:76)
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:923)
	at com.sun.mail.util.TraceInputStream.read(TraceInputStream.java:97)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at com.sun.mail.util.LineInputStream.readLine(LineInputStream.java:75)
	at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:1440)
	... 18 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
	at sun.security.validator.Validator.validate(Validator.java:271)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:312)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:221)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:128)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:636)
	... 36 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
	... 42 more

**Comment by ZhongFuCheng3y** [comment]
是什么邮件？qq还是163？能提供对应的账号入参吗？（账号和密码可不提供）

**Comment by wangenji2015** [comment]
> 是什么邮件？qq还是163？能提供对应的账号入参吗？（账号和密码可不提供）

qq邮箱
`{"host":"smtp.qq.com","port":465,"user":"xxx@qq.com","pass":"xxxx","from":"xxx@qq.com","starttlsEnable":"true","auth":true,"sslEnable":true}`

**Comment by wangenji2015** [comment]
sslEnable改为false也不行会报
```
2023-08-16 08:52:21.080 [dynamic-tp2] ERROR c.java3y.austin.handler.handler.impl.EmailHandler - EmailHandler#handler fail!cn.hutool.extra.mail.MailException: MessagingException: Exception reading response
	at cn.hutool.extra.mail.Mail.send(Mail.java:393)
	at cn.hutool.extra.mail.MailUtil.send(MailUtil.java:416)
	at cn.hutool.extra.mail.MailUtil.send(MailUtil.java:194)
	at cn.hutool.extra.mail.MailUtil.send(MailUtil.java:176)
	at com.java3y.austin.handler.handler.impl.EmailHandler.handler(EmailHandler.java:61)
	at com.java3y.austin.handler.handler.BaseHandler.doHandler(BaseHandler.java:61)
	at com.java3y.austin.handler.pending.Task.run(Task.java:66)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: javax.mail.MessagingException: Exception reading response;
  nested exception is:
	java.net.SocketTimeoutException: Read timed out
	at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:1462)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1260)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:370)
	at javax.mail.Service.connect(Service.java:297)
	at javax.mail.Service.connect(Service.java:156)
	at javax.mail.Service.connect(Service.java:105)
	at javax.mail.Transport.send0(Transport.java:168)
	at javax.mail.Transport.send(Transport.java:98)
	at cn.hutool.extra.mail.Mail.doSend(Mail.java:407)
	at cn.hutool.extra.mail.Mail.send(Mail.java:385)
	... 9 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at com.sun.mail.util.TraceInputStream.read(TraceInputStream.java:97)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at com.sun.mail.util.LineInputStream.readLine(LineInputStream.java:75)
	at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:1440)
	... 18 more
,params:TaskInfo(bizId=k92moCpVNk5hwZwBI5Ttl, messageId=k92moCpVNk5hwZwBI5Ttl, messageTemplateId=3, businessId=2000000320230816, receiver=[fg@qq.com], idType=50, sendChannel=40, templateType=20, msgType=10, shieldType=10, contentModel=EmailContentModel(title=发发发, content=苟富贵, url=null), sendAccount=5)
2023-08-16 08:52:23.337 [dynamic-tp2] INFO  com.java3y.austin.support.utils.LogUtils - {"bizId":"k92moCpVNk5hwZwBI5Ttl","businessId":2000000320230816,"ids":["fg@qq.com"],"logTimestamp":1692147143337,"messageId":"k92moCpVNk5hwZwBI5Ttl","state":70}
```

**Comment by wangenji2015** [comment]
和环境有关，应该是本地jdk问题？放服务器能行，还有链路追踪，只有配置上kafka才能查吗，rabbitmq可以吗

**Comment by ZhongFuCheng3y** [comment]
> 和环境有关，应该是本地jdk问题？放服务器能行，还有链路追踪，只有配置上kafka才能查吗，rabbitmq可以吗

目前只实现了kafka，要有链路追踪，还得把flink部署给起来。
